//! Standalone mock LLM server for load testing.
//! Responds to OpenAI-compatible /v1/chat/completions with a fake response.
//!
//! Usage:
//!   mock-server --port 9090 --latency-ms 20 --error-rate 0.02
//!
//! Then point your gateway.toml provider base_url at http://localhost:9090

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::Duration;

use axum::{
    Router,
    extract::{Path, State},
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::post,
    Json,
};
use clap::Parser;
use serde_json::{json, Value};

/// ~4 chars per token — the standard rough estimate.
fn estimate_tokens(text: &str) -> u32 {
    ((text.chars().count() as u32) / 4).max(1)
}

/// Collect all string values under "content"/"text" keys (covers OpenAI,
/// Anthropic and Gemini request shapes).
fn collect_input_text(v: &Value, out: &mut String) {
    match v {
        Value::Object(map) => {
            for (k, val) in map {
                match val {
                    Value::String(s) if k == "content" || k == "text" => {
                        out.push_str(s);
                        out.push(' ');
                    }
                    _ => collect_input_text(val, out),
                }
            }
        }
        Value::Array(items) => {
            for item in items { collect_input_text(item, out); }
        }
        _ => {}
    }
}

fn usage_for(body: &Value, reply: &str) -> (u32, u32) {
    let mut input = String::new();
    collect_input_text(body, &mut input);
    (estimate_tokens(&input), estimate_tokens(reply))
}

#[derive(Parser, Clone)]
#[command(name = "mock-server", about = "Fake LLM server for load testing")]
struct Args {
    #[arg(long, default_value = "9090")]
    port: u16,

    /// Simulated latency per request in ms
    #[arg(long, default_value = "10")]
    latency_ms: u64,

    /// Fraction of requests to fail (0.0 – 1.0)
    #[arg(long, default_value = "0.0")]
    error_rate: f64,

    /// HTTP status code used for simulated errors
    #[arg(long, default_value = "500")]
    error_status: u16,

    /// Number of fake prompt tokens in each response
    #[arg(long, default_value = "50")]
    prompt_tokens: u32,

    /// Number of fake completion tokens in each response
    #[arg(long, default_value = "25")]
    completion_tokens: u32,
}

#[derive(Clone)]
struct AppState {
    args: Arc<Args>,
    request_count: Arc<AtomicU64>,
    error_count: Arc<AtomicU64>,
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt().with_env_filter("info").init();

    let args = Args::parse();

    let state = AppState {
        args: Arc::new(args.clone()),
        request_count: Arc::new(AtomicU64::new(0)),
        error_count: Arc::new(AtomicU64::new(0)),
    };

    let app = Router::new()
        .route("/v1/chat/completions", post(handle_openai))
        .route("/v1/messages", post(handle_anthropic))
        .route("/v1beta/models/*path", post(handle_gemini))
        .route("/stats", axum::routing::get(handle_stats))
        .with_state(state);

    let addr = format!("0.0.0.0:{}", args.port);
    tracing::info!("Mock LLM server listening on {addr}");
    tracing::info!(
        "Latency: {}ms | Error rate: {:.1}%",
        args.latency_ms,
        args.error_rate * 100.0
    );

    let listener = tokio::net::TcpListener::bind(&addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

async fn should_error(state: &AppState) -> bool {
    let n = state.request_count.fetch_add(1, Ordering::Relaxed);
    // Simple deterministic error injection: error every 1/rate requests
    if state.args.error_rate > 0.0 {
        let period = (1.0 / state.args.error_rate).round() as u64;
        if period > 0 && n % period == 0 {
            state.error_count.fetch_add(1, Ordering::Relaxed);
            return true;
        }
    }
    if state.args.latency_ms > 0 {
        tokio::time::sleep(Duration::from_millis(state.args.latency_ms)).await;
    }
    false
}

async fn handle_openai(State(s): State<AppState>, body: Option<Json<Value>>) -> Response {
    if should_error(&s).await {
        return (
            StatusCode::from_u16(s.args.error_status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR),
            Json(json!({"error": {"message": "simulated error", "type": "mock_error"}})),
        )
            .into_response();
    }

    let reply = "This is a mock response generated by the Modo test server. It echoes realistic \
token accounting: prompt tokens are estimated from your request content and completion tokens \
from this reply, so analytics and cost views behave like a real provider.";
    let (prompt_tokens, completion_tokens) =
        usage_for(body.as_deref().unwrap_or(&Value::Null), reply);

    Json(json!({
        "id": format!("chatcmpl-{}", uuid::Uuid::new_v4()),
        "object": "chat.completion",
        "created": chrono::Utc::now().timestamp(),
        "model": "mock-gpt-4o",
        "choices": [{
            "index": 0,
            "message": { "role": "assistant", "content": reply },
            "finish_reason": "stop"
        }],
        "usage": {
            "prompt_tokens":     prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens":      prompt_tokens + completion_tokens
        }
    }))
    .into_response()
}

async fn handle_anthropic(State(s): State<AppState>, body: Option<Json<Value>>) -> Response {
    if should_error(&s).await {
        return (
            StatusCode::from_u16(s.args.error_status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR),
            Json(json!({"error": {"type": "api_error", "message": "simulated error"}})),
        )
            .into_response();
    }

    let reply = "Mock response from the Modo test server with realistic token accounting.";
    let (input_tokens, output_tokens) =
        usage_for(body.as_deref().unwrap_or(&Value::Null), reply);

    Json(json!({
        "id": format!("msg_{}", uuid::Uuid::new_v4()),
        "type": "message",
        "role": "assistant",
        "content": [{ "type": "text", "text": reply }],
        "model": "claude-mock",
        "stop_reason": "end_turn",
        "usage": {
            "input_tokens":  input_tokens,
            "output_tokens": output_tokens
        }
    }))
    .into_response()
}

async fn handle_gemini(State(s): State<AppState>, Path(_path): Path<String>, body: Option<Json<Value>>) -> Response {
    if should_error(&s).await {
        return (
            StatusCode::from_u16(s.args.error_status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR),
            Json(json!({"error": {"code": 500, "message": "simulated error"}})),
        )
            .into_response();
    }

    let reply = "Mock response from the Modo test server.";
    let (prompt_tokens, completion_tokens) =
        usage_for(body.as_deref().unwrap_or(&Value::Null), reply);

    Json(json!({
        "candidates": [{
            "content": { "parts": [{"text": reply}], "role": "model" },
            "finishReason": "STOP",
            "index": 0
        }],
        "usageMetadata": {
            "promptTokenCount":     prompt_tokens,
            "candidatesTokenCount": completion_tokens,
            "totalTokenCount":      prompt_tokens + completion_tokens
        }
    }))
    .into_response()
}

async fn handle_stats(State(s): State<AppState>) -> Json<serde_json::Value> {
    Json(json!({
        "total_requests": s.request_count.load(Ordering::Relaxed),
        "error_count":    s.error_count.load(Ordering::Relaxed),
        "config": {
            "latency_ms":        s.args.latency_ms,
            "error_rate":        s.args.error_rate,
            "prompt_tokens":     s.args.prompt_tokens,
            "completion_tokens": s.args.completion_tokens,
        }
    }))
}
